### ISSUE TITLE
local_moran does not inherit `zero.policy` or `NAOK` when using `lag.listw`

### ISSUE THREAD

**Issue by kaseyzapatka** [JosiahParry/sfweight#2] opened 2021-06-23 15:33 UTC
Hi @JosiahParry, 

Thanks for creating `sfweigth`, `tidyverse`-friendly approach is very much appreciated.  I have two questions I'm hoping you can provide some insight on for me. I'm trying to create LISA Maps to identify statistically significant clusters of non-Hispanic White neighborhoods in the suburbs. 

First, how does `sfweight` deal with empty geometries? I know the `spdep` package has the `na.action` function, but I didn't see anything in the documentation for `sfweight` regarding this. Perhaps, I'm jumping the gun here and you plan to include it?   I realize I can drop empty geometries (I do so in the second example code chunk) , but I'm not sure that is a long-term solution and what the implications are of this. What is best practice here or do you have any suggestions about how I can address this in `sfweight` or at least while you get the package up on CRAN? 

Second, I have missing data on the variable of interest--the variable for which I am trying lag--percent non-Hispanic White (pnhwht_). The variable has missing data because I'm only interested in creating LISA clusters for census tracts in the suburbs, not in the city proper, so I've set all tracts not in the suburbs to missing. This is also necessary for mapping too. Is there a way I deal with missing data on my var of interest while calculating the lag? When I run the sample code below, it throws the following error:

```
Error: Problem with `mutate()` column `pnhwht_suburb_lag`. ℹ `pnhwht_suburb_lag = st_lag(pnhwht_, nb, wts)`. x Variable contains non-finite values 
```

If I replace the missing values with zero in a mutate function before I calculate the lag, the function runs. However, I hesitate to do this because I'm not sure of the implications and I'm suspicious of the results. Do you have any thoughts on that?

Here's a [link to sample data](https://www.dropbox.com/sh/fvtcjlhwlrowx43/AADtQaLfAGdXPmcJIAl1UTL7a?dl=0). Thanks for your help!

```

# load data
ny_suburbs_sample <- read_sf(here("data/processed/analysis/new-york/ny_suburbs_sample.dbf")) %>% 
  glimpse()


# remove empty geometries so connectivity and weight creation functions will run
ny_suburbs_shp_no_na <- ny_suburbs_sample %>% 
  drop_na(geometry) %>% 
  # convert back to sf object
  st_as_sf() %>% 
    glimpse()


# connectivity and weights -----------------------------------------------------
test <- ny_suburbs_shp_no_na %>% 
  mutate(nb = st_neighbors(geometry), 
         wts = st_weights(nb),
         pnhwht_suburb_lag = st_lag(pnhwht_, nb, wts)) %>% 
  mutate(lisa_group = categorize_lisa(pnhwht_, pnhwht_suburb_lag)) %>% 
  glimpse()

```

**Comment by JosiahParry** [comment] 2021-06-23 17:15
Hey! Thanks for the issue. Super helpful! 

By default the `na_ok` argument is set to `FALSE`, if you set it to `TRUE` you should be a-okay! This is passed to the argument `NAOK` in `spdep::lag.listw()`. 

However, I didn't anticipate missing values in `categorize_lisa()` so as you'll see the below plots values of `""`. I'll push a change to fix that shortly. 

Let me know if this helps! 

```
library(sf)
library(sfweight)
library(tidyverse)

df <- read_sf("/Users/josiah/Downloads/lisa-maps/")


df %>% 
  # remove missing geometries
  drop_na(geometry) %>% 
  # convert back to sf object
  st_as_sf() %>% 
  transmute(nb = st_neighbors(geometry),
            wts = st_weights(nb),
            # specify `na_ok = TRUE`
            pnhwht_suburb_lag = st_lag(pnhwht_, nb, wts, na_ok = TRUE),
            lisa_group = categorize_lisa(pnhwht_, pnhwht_suburb_lag)) %>% 
  ggplot(aes(fill = lisa_group)) +
  geom_sf(color = "black", lwd = 0.1) +
  scale_fill_discrete(na.translate = FALSE)
```
![image](https://user-images.githubusercontent.com/13534508/123139974-c9885b80-d424-11eb-9694-ff951cf3b76d.png)

**Comment by JosiahParry** [comment] 2021-06-23 17:23
Categorization fixed in https://github.com/JosiahParry/sfweight/commit/36e4ffbe367198121cc279d0c31bf66e356e54e0. 

let me know how this works!

**Comment by kaseyzapatka** [comment] 2021-06-23 19:18
@JosiahParry, great this worked perfectly. leaving the final product here in case others want to see! thanks so much!



[test_plot.pdf](https://github.com/JosiahParry/sfweight/files/6704361/test_plot.pdf)

**Comment by JosiahParry** [comment] 2021-06-23 19:40
Wonderful! Keep the feedback coming! Would love to see what you do :)

**Comment by kaseyzapatka** [comment] 2021-11-11 22:14
@JosiahParry, I ran into another error. When I try to run the `local_moran` function, it throws the following error: 

```
Error: Problem with `mutate()` column `lisa`. ℹ `lisa = local_moran(prburden_all_13as19, nb, wts)`. x lengths of 'breaks' and 'labels' differ
```

I think it's because there is one observation where the weight is `NULL,`  there are no neighbors, and the lagged value is `NA`.  See screen shot of this one observation below.  When I drop that tract, it runs fine. 

Is the fix to add something `na_ok = TRUE` or something about zero neighbors or NULL weights to the `local_moran` function?

Let me know if this isn't clear and I can try to create a reproducible example this weekend. 

![Uploading Screen Shot 2021-11-11 at 5.04.54 PM.png…]()

**Comment by JosiahParry** [comment] 2021-11-13 16:38
Hey! Can you provide a reprex for simplicity sake? 
I cannot create a weights variable when I have a nb element equal to 0.

**Comment by kaseyzapatka** [comment] 2021-12-03 00:29
Hey @JosiahParry, 

Here's the code and a [dropbox to the data](https://www.dropbox.com/sh/gxacg6txrh5v59b/AACVya8iBl86E2SXKh7DnFmka?dl=0).


```

chp2_shp %>% 
# prep data -----------
  
# limit to 2013
  filter(year == "2013") %>%
  # filter out empty geometries
  filter(!st_is_empty(geometry)) %>%  
  
  # create neighborhood connectivity and weights
  transmute(nb = st_neighbors(geometry),
            wts = st_weights(nb, allow_zero = TRUE), 
            prburden_lag = st_lag(prburden, nb, wts, na_ok = TRUE),
            prburden = prburden,
            year = year, 
            tractid = tractid, 
            lisa = local_moran(prburden, nb, wts),
            lisa_group = categorize_lisa(prburden, prburden_lag), 
            threshold = 0.05) %>% 
  # unpack
  unnest(lisa) %>%
  
  # convert geometry
  st_as_sf() %>%
  
  # ggplot -----------
  ggplot(aes(fill = lisa_category)) + 
  geom_sf(color = "black", lwd = 0.25) +
  scale_fill_manual(values = c("#196191", "#5EBFFF", "white", "#DE9B3C", "#915A0A")) + 
  theme_void()


```

End results is to create a LISA map reporting significant clusters of rent burden rates across metro area. For various reasons, there will be missing data. `local_moran` produces following error when I run above code because it says there is missing data used in the function. 

```
Error: Problem with `mutate()` column `lisa`. ℹ `lisa = local_moran(prburden, nb, wts)`. x missing values in object 

```

The following code shows missing values on prburden, which I think is the source. Maybe it just needs a similar `na_ok = TRUE`? I know the `spdep` function `localmoran` sets `na_ok = NULL`. 

```

chp2_shp %>% 
# prep data -----------
  
# limit to 2013
  filter(year == "2013") %>%
  # filter out empty geometries
  filter(!st_is_empty(geometry)) %>%  
  
  # create neighborhood connectivity and weights
  transmute(nb = st_neighbors(geometry),
            wts = st_weights(nb, allow_zero = TRUE), 
            prburden_lag = st_lag(prburden, nb, wts, na_ok = TRUE),
            prburden = prburden,
            year = year, 
            tractid = tractid) %>% View()

```

**Comment by JosiahParry** [comment] 2021-12-03 00:43
Please try this with the na_ok argument. This calls spdep under the hood!
If that doesn’t work, please provide a reproducible example so I can debug
myself! Thanks!

**Comment by kaseyzapatka** [comment] 2021-12-03 00:59
forgot to mention I originally tried that. It says it's an unused argument : 

```
Error: Problem with `mutate()` column `lisa`. ℹ `lisa = local_moran(prburden, nb, wts, na_ok = TRUE)`. x unused argument (na_ok = TRUE)

```

Does my reprex in the prior post not work? I'm not sure how to reproduce this using other data.

**Comment by JosiahParry** [comment] 2021-12-03 18:30
It is not a reproducible example because I cannot run your code on my machine and have the same output. For example, `chp2_shp` is not defined anywhere in your code.

Refer to https://www.tidyverse.org/help/ for more. 

You can use `dput(object)` to provide the code that is used to create an object.

**Comment by JosiahParry** [comment] 2021-12-03 20:29
It appears that the issue is stemming from missing values in your variable of interest. These are not handled properly by `sfweight`. This can be fixed in this line https://github.com/JosiahParry/sfweight/blob/e9b083f87ca5e3638fa92cb20f8f7f9a14041574/R/moran_test.R#L65

**Comment by kaseyzapatka** [comment] 2022-01-03 19:51
Hi @JosiahParry, 

Been thinking about how to best present this to you for a while now and been forced to confront it since I'm writing up this dissertation chapter.  I tried making a reproducible example using `reprex()` and `dput()` like you suggested, but there's too many observations when I use `dput()` to properly recreate the data structure. Not sure if there is preloaded dataset with spatial data, so that didn't seem to be a reasonable approach.  I thought about taking a random sample, but worried that such an approach would miss the problematic observations. 

If I understand the error correctly, it's because the *rburden,* *wts,* and *nb* variables in the last `local_moran()` step are not the same length.  I think this is because there are two tract observations with 0 neighborhoods and therefore NULL wts, ensuring they are not the same length as *rburden* variable.

Here's the specific error, my code, and a dropbox link to the data. This should be reproducible. My apologies I couldn't follow the correct `reprex()` protocol. If you remove the "#" on the line that filters out the two tractids, the code runs successfully because they are the two tracts that don't have neighborhoods and therefore NULL weights. **So, I think the solution --as you already proposed--is to ensure `local_moran` inherits `zero.policy `or `na_ok`.**


```
Error: Problem with `mutate()` column `lisa`. ℹ `lisa = local_moran(burden, nb, wts)`. x lengths of 'breaks' and 'labels' differ

```

```

# load all packages using xfun, package2 will install if not available
xfun::pkg_attach2(c("tidyverse",
                    "tidycensus",
                    "tmap",
                    "mapview",
                    "sf",
                    "here",
                    "spatialreg",
                    "spdep",
                    "sfweight"))
  
# load data
data <- st_read(here("data/processed/shapefiles/github/tracts_nymetro.shp")) %>%
    st_transform(4269) %>% glimpse()
  

# LISA plot 
data %>% 
  # filter two tracts with no neighbors and NULL weights
  # filter(tractid != "36081107201" & tractid != "36081091601") %>%
    # create neighborhood connectivity and weights
    transmute(burden = burden,
              year = year, 
              tractid = tractid, 
              nb = st_neighbors(geometry),
              wts = st_weights(nb, allow_zero = TRUE), 
              burden_lag = st_lag(burden, nb, wts, na_ok = TRUE),
              lisa = local_moran(burden, nb, wts)) %>% 
  
  # unpack
  unnest(lisa) %>%

  # convert geometry
  st_as_sf() %>%

  # ggplot -----------
  ggplot(aes(fill = lisa_category)) +
  geom_sf(color = "black", lwd = 0.25) +
  scale_fill_manual(values = c("#196191", "#5EBFFF", "white", "#DE9B3C", "#915A0A")) +
  theme_void()

````

Dropbox [link to the data](https://www.dropbox.com/sh/4x8j8f1ztwlujxs/AAD70Bzc4JavpBhPIWZVDqPfa?dl=0) used above.

This code helped me visualize the problem. For example, tractid == "36081107201" has no neighbors and therefore the weight matrix is set to NULL , whereas tractid == "36005000400"  does have neighbors and therefore has valid neighbor and wights values.

```
# visualize problematic tracts
data %>% 
    # create neighborhood connectivity and weights
    transmute(burden = burden,
              year = year, 
              tractid = tractid, 
              nb = st_neighbors(geometry),
              wts = st_weights(nb, allow_zero = TRUE), 
              burden_lag = st_lag(burden, nb, wts, na_ok = TRUE)) %>% 
  filter(tractid == "36081107201" | tractid == "36005000400") %>%
  View()
```


Thanks for your help and developing the package. Looking forward to seeing it deployed on CRAN. 

Kasey

**Comment by JosiahParry** [comment] 2022-01-04 18:36
Hey Kasey, I appreciate this. I am working on this presently and hope to have it done in the next couple of days. Apologies for any challenges this may have for your dissertation!

**Comment by kaseyzapatka** [comment] 2022-01-04 18:39
Thanks @JosiahParry! No worries. Filtering out the problematic tracts works for now, but a long term solution is why I registered the comment. Thanks again. Really is a great package.

**Comment by JosiahParry** [comment] 2022-01-08 15:13
I've been working on a rewrite of this package. It can be found at https://github.com/JosiahParry/sfdep. The functionality is identical and the `local_moran()` function there works with missing values. The documentation is very sparse at the moment . However, these packages utilize spdep so if you ever need help navigate to the related documentation there. 

The below is an example of how to compute the lisa when NA is present.
```
 lisa <- sfweight::acs %>%
   mutate(nb = st_contiguity(geometry),
          wt = st_weights(nb),
          moran = local_moran(med_house_income, nb, wt, na.action = na.pass, zero.policy = TRUE))
```

**Closed** 2022-01-10 14:05 UTC
